"""
Admin authentication via JWT (Authorization: Bearer) only.
"""
from datetime import datetime, timedelta, timezone
from jose import jwt, JWTError
from fastapi import HTTPException, Depends
from fastapi.security import HTTPBearer, HTTPAuthorizationCredentials
from app.core.config import settings

security = HTTPBearer(auto_error=False)


def create_access_token() -> str:
    """Generate a JWT access token for the admin."""
    expire = datetime.now(timezone.utc) + timedelta(hours=settings.JWT_EXPIRY_HOURS)
    to_encode = {
        "sub": "admin",
        "role": "admin",
        "exp": expire,
    }
    return jwt.encode(to_encode, settings.JWT_SECRET, algorithm=settings.JWT_ALGORITHM)


async def verify_admin(
    credentials: HTTPAuthorizationCredentials | None = Depends(security),
):
    """
    Dependency for protecting admin routes.
    Accepts: Authorization: Bearer <JWT> (generated by POST /admin/login)
    """
    if not credentials:
        raise HTTPException(status_code=401, detail="Unauthorized")

    try:
        payload = jwt.decode(
            credentials.credentials,
            settings.JWT_SECRET,
            algorithms=[settings.JWT_ALGORITHM],
        )
        if payload.get("role") == "admin":
            return True
    except JWTError:
        pass

    raise HTTPException(status_code=401, detail="Unauthorized")
